enableStrictSsl: false

httpTimeout: 12000000

nodeLinker: node-modules

#npmAlwaysAuth: false

#npmPublishRegistry: 'https://some-art.com/artifactory/api/npm/portfolio-yues-it-npm/'

#npmRegistryServer: 'https://some-art.com/artifactory/api/npm/portfolio-yues-it-npm/'

#npmAuthToken: 'some token from a virtual repository jfrog (Repositories -> Virtual -> Set me up -> Configure -> Generate token)'

yarnPath: .yarn/releases/yarn-berry.cjs
